---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.appName }}
  namespace: handson
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ template "docker-image" . }}
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 1
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 60
              timeoutSeconds: 10
              periodSeconds: 10
              failureThreshold: 1
          ports:
            - containerPort: 80
          env:
            - name: JAVA_OPTS
              value: {{ .Values.javaopts }}  {{ template "mongo-password" . }}
      imagePullSecrets: 
       - name: regcred
      restartPolicy: Always